import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import ReactQueryProvider from '@/components/providers/ReactQueryProvider';
import { ToastProvider } from '@/components/providers/toast-provider';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const satoshi = localFont({
    src: [
        {
            path: '../public/fonts/Satoshi-Variable.ttf',
            style: 'normal',
        },
    ],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={satoshi.className}>
                <ReactQueryProvider>
                    <ToastProvider />
                    {children}
                </ReactQueryProvider>
            </body>
        </html>
    );
}
